# Welcome to Jekyll!

# Website settings
title: "Marcin Moskala"
description: "The web page of Marcin Moskala"
keywords: "Marcin, Moskala, github, Kotlin, multiplatform, Kotlin Academy, Marcin Moskala"
baseurl: "/"
url: "http://www.marcinmoskala.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Marcin Moskala'
  first_name: 'Marcin'
  last_name: 'Moskala'
  email: 'marcinmoskala@gmail.com'
  facebook_username: 'mmoskala'
  github_username: 'MarcinMoskala'
  twitter_username: 'marcinmoskala'
  head_img: 'static/img/landing/marcin.jpg'
  desc: 'I am Android Kotlin developer, telecommunicant and machine learning passionate'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''
    in_menu: true
    
  - id: 'services'
    i18n: 'nav.services'
    name: 'Services'
    tpl: 'services.html'
    css: 'timeline'
    in_menu: true

  - id: 'talks'
    i18n: 'nav.talks'
    name: 'Talks'
    tpl: 'talks.html'
    css: 'timeline'
    in_menu: true

  - id: 'books'
    i18n: 'nav.books'
    name: 'Books'
    tpl: 'books.html'
    css: ''
    in_menu: false

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Key publications'
    tpl: 'publications.html'
    css: 'timeline'
    in_menu: false

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'
    in_menu: true

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'
    in_menu: true

  - id: 'consulting'
    i18n: 'nav.consulting'
    name: 'Contact'
    tpl: 'consulting.html'
    css: 'testimonials navy-section'
    in_menu: true

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'pl'
    flag: 'static/img/flags/Poland.png'

# blog img path
img_path: 'http://marcinmoskala.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# google analytics
ga:
  id: UA-92159206-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
