- i18n: workshops
  img: fa fa-chalkboard-teacher
  url: "https://kt.academy"

- i18n: consultations
  img: fa fa-comments
  url: "mailto:marcinmoskala@gmail.com"

- i18n: other
  img: fa fa-code
  url: "mailto:marcinmoskala@gmail.com"